version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka-service:
    image: wurstmeister/kafka:2.13-2.7.0
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - kafka:/var/run/docker.sock
    depends_on:
      - zookeeper

  postgres:
    image: postgres:12-alpine
    env_file: ./postgres.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432

  pgadmin:
    image: dpage/pgadmin4:4
    env_file: ./pgadmin.env
    ports:
      - 8000:80
    links:
      - postgres:postgres


volumes:
  pgdata:
  kafka:

