version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka-service:
    image: wurstmeister/kafka:2.13-2.7.0
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - kafka:/var/run/docker.sock
    depends_on:
      - zookeeper

volumes:
  kafka:

